import { takeEvery } from "@redux-saga/core/effects";
import {
    assignProjectsToContractorOrEstimator,
    copyAppendixToGCFolder,
    fetchAllAdmin,
    fetchAllContractors,
    fetchAllOrganizations,
    fetchAssignedContractorsToProject,
    fetchBaselineBidBook,
    fetchEmailMetaData,
    generateBidbookCopies,
    inviteCollaborators,
    removeOrganizationAssignedToProject,
    removeProjectsAssignedToContractorOrEstimator,
    sendForRevision,
    updateBidStatus,
    updateEmailMetaData,
    createNewCollaborator,
    fetchAssignedContractorsToProjectByOrganization,
    removeCollaboratorFromProject,
    sendInvite,
    createNewBillingOpportunity,
    fetchBillingOpportunityID,
    createBidRequest,
    fetchAssignedUsersToProject,
    computeBidItemsExtended,
} from "./rfp-manager-operations";
import { actions } from "./rfp-manager-slice";

export const rfpProjectManagerSaga = [
    takeEvery(actions.fetchAssignedContractorListStart.type, fetchAssignedContractorsToProject),
    takeEvery(actions.fetchAllOrganizationsStart.type, fetchAllOrganizations),
    takeEvery(actions.fetchAllContractorsStart.type, fetchAllContractors),
    takeEvery(actions.fetchAllAdminStart.type, fetchAllAdmin),
    takeEvery(actions.assignContractorOrEstimatorStart.type, assignProjectsToContractorOrEstimator),
    takeEvery(actions.sendForRevisionStart.type, sendForRevision),
    takeEvery(actions.updateEmailMetaDataStart.type, updateEmailMetaData),
    takeEvery(actions.updateBidStatusStart.type, updateBidStatus),
    takeEvery(actions.fetchEmailMetaDataStart.type, fetchEmailMetaData),
    takeEvery(actions.fetchBaselineBidBookStart.type, fetchBaselineBidBook),
    takeEvery(actions.removeOrganizationFromProjectStart.type, removeOrganizationAssignedToProject),
    takeEvery(
        actions.removeUsersFromProjectStart.type,
        removeProjectsAssignedToContractorOrEstimator,
    ),
    takeEvery(actions.removeCollaboratorStart.type, removeCollaboratorFromProject),
    takeEvery(actions.createBidBookStart.type, generateBidbookCopies),
    takeEvery(actions.sendInviteStart.type, sendInvite),
    takeEvery(actions.copyAppendixToGCFolderStart.type, copyAppendixToGCFolder),
    takeEvery(actions.inviteCollaboratorsStart.type, inviteCollaborators),
    takeEvery(actions.createNewCollaboratorStart.type, createNewCollaborator),
    takeEvery(actions.createBillingOpportunityStart.type, createNewBillingOpportunity),
    takeEvery(
        actions.fetchAssignedContractorListForOrganizationStart.type,
        fetchAssignedContractorsToProjectByOrganization,
    ),
    takeEvery(actions.fetchBillingOpportunityIDStart.type, fetchBillingOpportunityID),
    takeEvery(actions.createBidRequestStart.type, createBidRequest),
    takeEvery(actions.fetchAssignedUsersListStart.type, fetchAssignedUsersToProject),
    takeEvery(actions.computeBidItemExtendedStart.type, computeBidItemsExtended),
];
