import { takeEvery, takeLatest } from "@redux-saga/core/effects";
import {
    fetchSingleProject,
    fetchProductionProject,
    updateSingleProject,
    createDesignDocuments,
    getDesignDocuments,
    deleteDesignDocuments,
    refetchDesignDocuments,
    getKeyPeople,
    getFileDownloadLink,
    getRfpBidStatusDeatils,
    getLeveledBidDocuments,
    getPackages,
    getQuestionsAndAnswers,
    getQuestionResponses,
    assignQuestionResponse,
    fetchSpecsOptionsAvailable,
    getInventoryList,
    fetchRenoParametersAvailable,
    fetchRenoItems,
    fetchApprovalChangeOrders,
    fetchMonthlySpendAnalysis,
    fetchProjectBudget,
    fetchRenoTimeByUnit,
    fetchMonthlyTurnedUnits,
    fetchRenovationProgress,
    fetchUnitStatusMap,
} from "./operation";

import { actions } from "./slice";
import {
    addNewMaterialItem,
    addRenovationItems,
    contactTailorbird,
    createRenoItemsFromExistingProject,
    getBasePackage,
    getPackageContent,
    getProjectCodices,
    getProjectContainer,
    getProjects,
    getRenovationItems,
    refreshRenovationItems,
    updateMultipleRenovationItems,
    updateSingleProjectStatus,
} from "./renovation-wizard-v2/operations";

export const SingleProjectDetailsSaga = [
    takeEvery(actions.createDesignDocumentsStart, createDesignDocuments),
    takeEvery(actions.getDesignDocumentsStart, getDesignDocuments),
    takeEvery(actions.fetchProjectDataStart.type, fetchSingleProject),
    takeEvery(actions.fetchProductionProjectStart.type, fetchProductionProject),
    takeEvery(actions.fetchApprovalChangeOrderStart.type, fetchApprovalChangeOrders),
    takeEvery(actions.fetchMonthlySpendAnalysisStart.type, fetchMonthlySpendAnalysis),
    takeEvery(actions.fetchProjectBudgetStart.type, fetchProjectBudget),
    takeEvery(actions.fetchRenoTimeByUnitStart.type, fetchRenoTimeByUnit),
    takeEvery(actions.fetchMonthlyTurnedUnitsStart.type, fetchMonthlyTurnedUnits),
    takeEvery(actions.fetchRenovationProgressStart.type, fetchRenovationProgress),
    takeEvery(actions.fetchUnitStatusMapStart.type, fetchUnitStatusMap),
    takeEvery(actions.updateSingleProjectStart.type, updateSingleProject),
    takeEvery(actions.DeleteDesignDocumentsStart, deleteDesignDocuments),
    takeLatest(actions.DeleteDesignDocumentsSuccess, refetchDesignDocuments),
    takeEvery(actions.fetchKeyPeopleStart, getKeyPeople),
    takeEvery(actions.getFileDownloadStart, getFileDownloadLink),
    takeEvery(actions.getRfpBidStatusDeatilsStart, getRfpBidStatusDeatils),
    takeEvery(actions.getLeveledBidDocumentsStart, getLeveledBidDocuments),
    takeEvery(actions.fetchPackagesStart, getPackages),
    takeEvery(actions.fetchQuestionsAndAnswersStart, getQuestionsAndAnswers),
    takeEvery(actions.fetchQuestionResponssesStart, getQuestionResponses),
    takeEvery(actions.fetchInventoryListStart, getInventoryList),
    takeEvery(actions.assignQuestionResponseStart, assignQuestionResponse),
    takeEvery(actions.fetchSpecsOptionsStart, fetchSpecsOptionsAvailable),
    takeEvery(actions.fetchRenoParametersStart, fetchRenoParametersAvailable),
    takeEvery(actions.fetchRenoItemsStart, fetchRenoItems),
    // reno-wizard-v2 sagas
    takeEvery(actions.updateSingleProjectStatusStart, updateSingleProjectStatus),
    takeEvery(actions.contactTailorbird, contactTailorbird),
    takeEvery(actions.getProjectContainerStart, getProjectContainer),
    takeEvery(actions.getProjectsStart, getProjects),
    takeEvery(actions.getRenovationItemsStart, getRenovationItems),
    takeLatest(actions.refreshRenovationItems, refreshRenovationItems),
    takeEvery(actions.getBasePackageStart, getBasePackage),
    takeEvery(actions.getPackageContentStart, getPackageContent),
    takeEvery(actions.updateRenovationItemsStart, updateMultipleRenovationItems),
    takeEvery(actions.addRenovationItemsStart, addRenovationItems),
    takeEvery(actions.createProjectScopeDocumentStart, createDesignDocuments),
    takeEvery(actions.createRenoItemsFromExistingProjectStart, createRenoItemsFromExistingProject),
    takeEvery(actions.getProjectCodicesStart, getProjectCodices),
    takeEvery(actions.getProjectScopeDocumentStart, getDesignDocuments),
    takeEvery(actions.addMaterialSpecStart, addNewMaterialItem),
];
