import initAjaxState from "../initAjaxState.json";
import { STEPS_NAME } from "modules/single-project/contants";

export const INITIAL_RENO_TIME_TABLE_COLUMNS = [
    "unit_number",
    "unit_type",
    "floor_plan_type",
    "inventory",
];

export default {
    ...initAjaxState,
    projectDetails: {
        id: "",
        name: "",
        organization_id: "",
        streetAddress: "",
        city: "",
        state: "",
        ownershipGroupId: "",
        owner: "",
        createdAt: "",
        propertyType: "",
        propertyId: "",
        projectType: "",
        startDate: "",
        endDate: "",
        approximateUnitCount: "",
        projectStatus: "",
        package_id: "",
        system_remarks: {},
        organization: {
            id: null,
            name: "",
        },
    },
    keyPeople: [],
    renovationWizard: {
        isInitial: true,
        currentInventory: {},
        inventoryList: { ...initAjaxState, data: [] },
        renoItemList: { ...initAjaxState, data: {} },
        uploadDetails: [],
        packageList: { ...initAjaxState, data: [] },
        navigation: {
            currentStep: STEPS_NAME.WELCOME,
            steps: [STEPS_NAME.WELCOME],
            ...initAjaxState,
        },
        rooms: { loading: false, data: [] },
        questionAnswerData: {
            currentCategoryId: null,
            currentQuestionId: null,
            data: [],
            originalResponse: [],
            skippedCategorys: [],
            isReachedLastQuestionOnSurvey: false,
            isPreviousQuestionExists: false,
            savingChanges: false,
            specOptions: { loading: false, data: {} },
            specParameters: { loading: false, data: {} },
        },
        questionResponses: { loadind: false, data: [] },
        breadcrumsData: [
            {
                name: "Program Details",
                status: "pending",
                icon: "new program",
                subset: null,
                categoryId: null,
            },
            {
                name: "Select Package",
                status: "pending",
                icon: "package",
                subset: null,
                categoryId: null,
            },
            {
                name: "Select Rooms",
                status: "pending",
                icon: "rooms",
                subset: null,
                categoryId: null,
            },
        ],
        breadCrumbTopLevel: {
            data: [
                {
                    name: "Program Details",
                    icon: "new program",
                    stepName: "inventory",
                    categoryId: null,
                    isCurrent: true,
                    isDone: false,
                    id: "program_details",
                },
                {
                    name: "Select Package",
                    icon: "package",
                    stepName: "package",
                    categoryId: null,
                    isCurrent: false,
                    isDone: false,
                    id: "select_package",
                },
                {
                    name: "Select Rooms",
                    icon: "rooms",
                    stepName: "rooms",
                    categoryId: null,
                    isCurrent: false,
                    isDone: false,
                    id: "select_rooms",
                },
            ],
        },
    },
    RFP: {
        leveledBidSheets: [],
        bidStatistics: [],
        contracts: [],
    },
    production: { haveAccessToProduction: false, supportEmail: "support@tailorbird.us" },
    projectAnalytics: {
        renovationProgress: {
            totalUnitsInprop: 0,
            totalRenoUnits: 0,
            completed: "",
            inprogress: "",
            notStarted: "",
            details: [],
        },
        renovationTime: {
            renovationTimePerUnit: "",
            averageNoOfUnitsTurnedPerMonth: "",
            renoTimeByUnit: {
                columns: INITIAL_RENO_TIME_TABLE_COLUMNS,
                data: [],
                avgRenoTimePerUnit: undefined,
            },
            monthByMonthUnitsTurned: [],
        },
        spendAnalysis: {
            estimatedBudget: undefined,
            actualSpend: undefined,
            estimatedWavg: "",
            avgWavg: "",
            budgetApprovalsAndChangeOrders: [],
            spendAnalysisMonthByMonth: [],
        },
    },
    loading: false,
    renovationWizardV2: {
        loading: false,
        renovationItems: { ...initAjaxState, data: [] },
        projectPackageContents: { ...initAjaxState, data: {} },
        projectContainer: { ...initAjaxState, data: [] },
        projectCodices: { ...initAjaxState, data: [] },
        projects: { ...initAjaxState, data: [] },
        uploadedFiles: { ...initAjaxState, data: [] },
        basePackage: { ...initAjaxState, data: {} },
        notes: "",
        submitted: false,
        currentStep: 0,
    },
    updating: false,
};
